# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
absl-py
antlr4-python3-runtime
audioread
blas
brotli-python
bzip2
ca-certificates
cachetools
certifi
cffi
charset-normalizer
colorama
contourpy
cuda-cccl
cuda-cudart
cuda-cudart-dev
cuda-cupti
cuda-libraries
cuda-libraries-dev
cuda-nvrtc
cuda-nvrtc-dev
cuda-nvtx
cuda-runtime
cycler
decorator
einops
filelock
fonttools
freetype
google-auth
google-auth-oauthlib
grpcio
hydra-core
idna
importlib-metadata
importlib-resources
intel-openmp
jinja2
joblib
kiwisolver
lcms2
lerc
libcublas
libcublas-dev
libcufft
libcufft-dev
libcurand
libcurand-dev
libcusolver
libcusolver-dev
libcusparse
libcusparse-dev
libdeflate
libffi
libhwloc
libiconv
libjpeg-turbo
libnpp
libnpp-dev
libnvjpeg
libnvjpeg-dev
libpng
librosa
libsqlite
libtiff
libuv
libwebp-base
libxcb
libxml2
libzlib
llvmlite
markdown
markupsafe
matplotlib
mkl
mkl-service
mkl_fft
mkl_random
mpmath
msgpack-python
networkx
ninja
numba
numpy
numpy-base
oauthlib
omegaconf
openjpeg
openssl
packaging
pandas
pesq
pillow
pip
platformdirs
pooch
protobuf
pthread-stubs
pyasn1
pyasn1-modules
pycparser
pyopenssl
pysocks
pystoi
python
python-dateutil
python-graphviz
python-tzdata
python_abi
pytorch
pytorch-cuda
pytorch-mutex
pytz
pyyaml
requests
requests-oauthlib
rsa
scikit-learn
scipy
setuptools
six
sortedcontainers
pysoundfile
soxr
sympy
tbb
tensorboard
tensorboard-data-server
threadpoolctl
tk
torchaudio
torchvision
tqdm
typing-extensions
typing_extensions
urllib3
werkzeug
wheel
win_inet_pton
xorg-libxau
xorg-libxdmcp
xz
yaml
zipp
zstd
